name: AbuBatta-Live-Bot
on:
  workflow_dispatch:
jobs:
  trade:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Freqtrade
        run: |
          pip install freqtrade

      - name: Run Bot Live
        run: |
          freqtrade trade --config config.json --strategy SampleStrategy --dry-run
